Добавляет новые компоненты, добавляет маршрутизацию
htmlacademy-react/1031945-guess-melody-5 pull request #3
Opened 2020-10-08 13:44 UTC by Krubob

2020-10-09 18:09 UTC, AKolodeev requested changes
Привет! В целом все нормально, нужно немного оптимальнее задать роутинг.

2020-10-09 18:09 UTC, AKolodeev commented on src/components/app/app.jsx
> +          <ArtistQuestionPage />
Используй свойство `component` у `Route` (см. https://reactrouter.com/web/api/Route/component)

2020-10-09 18:09 UTC, AKolodeev commented on src/components/app/app.jsx
> +          <WelcomePage errorsCount={errorsCount} />
Используй свойство `render` на `Route` (см. https://reactrouter.com/web/api/Route/render-func)

2020-10-10 19:03 UTC, Krubob commented on src/components/app/app.jsx
> +          <WelcomePage errorsCount={errorsCount} />
Ок, а почему так будет лучше?

2020-10-12 06:44 UTC, AKolodeev commented on src/components/app/app.jsx
> +          <WelcomePage errorsCount={errorsCount} />
В принципе, это можно делать любым способом (следуя тому, который принят в команде, конечно). По-моему мнению, это просто короче без вреда для читаемости. Так что в принципе, ничего плохого не случится, если бы ты и старый вариант оставил.

2020-10-12 06:44 UTC, merged